### ISSUE TITLE
frida_injector_inject_library_file_sync  Segmentation fault: 11

### ISSUE THREAD

**Issue by ChrisYang2009** [oleavr/ios-inject-custom#2]
Hi, what might be the reason of `Segmentation fault: 11` ?

iOS 11.3.1

**Comment by ChrisYang2009** [comment]
and one more question:
what's the equivalent JS/frida-cli api of `frida_injector_inject_library_file_sync ` ?

**Comment by oleavr** [comment]
Have a look at the crash report (you can use Xcode to pull it from the device).

The equivalent frida-core API from Node.js is: `injectLibraryFile()` on the `Device` object. (Similarly it's `inject_library_file()` on the `Device` object from Python.)
