### ISSUE TITLE
a problem when compile inject.c for macOS

### ISSUE THREAD

**Issue by didongke** [oleavr/ios-inject-custom#3]
I'd like to run this test on macOS 10.13.6.
So I compile inject.c on macOS 10.13.6（xcode 9.4.1, frida-devkit-macos 12.2.26）as following，just like it in the Makefile:

mac$ gcc -o inject -I. -L. -lfrida-core -Wl,-framework,Foundation,-framework,AppKit  -lresolv   inject.c 
Undefined symbols for architecture x86_64:
  "_audit_token_to_pid", referenced from:
      __frida_handshake_port_perform_exchange_as_receiver in libfrida-core.a(darwin_port-glue.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I find a similar problem in this page: 
https://github.com/nowsecure/frida-cycript/issues/7

But I don’t know how to resolve it.

**Comment by oleavr** [comment]
Add `-lbsm`. Cheers!

**Comment by didongke** [comment]
Thank you. The problem has been solved. The program has run successfully on macOS 10.13.6.

**Comment by didongke** [comment]
Another question is that I'd like to compile agent.dylib within xcode 9.4.1 on macOS 10.13.6.
Agent.dylib has been compiled successfully, but victim fails when running inject program.
The error information is " Segmentation fault : 11 ".

It's because that I want to modify agent.c and use CaptainHook to hook objective-c code.
https://github.com/rpetrich/CaptainHook

Do you think this is feasible?

**Comment by oleavr** [comment]
For now the agent may only depend on libSystem/libraries guaranteed to already be loaded by the target process. You'd have to improve Frida's injector so it supports dynamically loading dependencies not already present. PR welcome!

**Comment by didongke** [comment]
I change xcode's Build Settings as following:
Implicitly Link Objective-C Runtime Support    ----  No
Objective-C Automatic Reference Counting     ----  No

The generated agent.dylib can be injected correctly.
But It fails if setting to Yes even though agent.c do nothing.

Does it mean that agent can't support Objective-C ?

**Comment by oleavr** [comment]
Objective-C is iffy since it may make it impossible to unload the module, if your .dylib contains classes (meaning they get registered with the runtime, and can't be unregistered, at least as far as I can remember). I would encourage you to study `Gum.Darwin.Mapper`, used by Frida's injector:
https://github.com/frida/frida-gum/blob/master/gum/backend-darwin/gumdarwinmapper.c
It's an out-of-process dynamic linker allowing agents to be injected into processes that are sandboxed.

**Comment by didongke** [comment]
Before trying Frida，I tried another method  https://github.com/rentzsch/mach_inject

On macOS 10.13.6, It can inject dynamic library written in Objecitve-C into TextEdit, Microsoft office(Word/Excel/PowerPoint), but fails injecting dynamic library into Safari and Apple office(Pages/Numbers/Keynot).

The error occurs on line 109 in load_bundle.c :
void *image = dlopen(bundleExecutableFileSystemRepresentation, RTLD_NOW);
https://github.com/rentzsch/mach_inject/blob/semver-1.x/mach_inject_bundle_stub/load_bundle.c

The error information is:
dlopen(…/agent.dylib): no suitable image found.
Did find: …/agent.dylib: code signature in(…/agent.dylib) 
not valid for use in process using Library Validation: 
mapping process is a platform binary, but mapped file is not

SIP has been disabled and agent.dylib is not been signed.
I wonder if Safari and Apple office(Pages/Numbers/Keynot) really can be injected.

**Comment by didongke** [comment]
**I don't quite understand what you mean.**

`1、For now the agent may only depend on libSystem/libraries guaranteed to already be loaded by the target process. You'd have to improve Frida's injector so it supports dynamically loading dependencies not already present.`
**My question :** It fails to inject agent.dylib with Objective-C runtime support because that agent.dylib depends on Objective-C runtime library and can’t be loaded dynamically. Is it right?

`2、Objective-C is iffy since it may make it impossible to unload the module, if your .dylib contains classes (meaning they get registered with the runtime, and can't be unregistered, at least as far as I can remember). `
**My question :** How does it affect injecting agent.dylib that it is impossible to unload the module?
