### ISSUE TITLE
Is there any way to inject remotely?

### ISSUE THREAD

**Issue by L1MeN9Yu** [oleavr/ios-inject-custom#5]
Is there any way to use `FridaInjector` to inject library through  a macOS handle `FridaSession` to a jailbreak iOS device running `frida-server`?

The `FridaScript` works perfected but I didn't find any api to do this for `FridaInjector`.

**Comment by oleavr** [comment]
Yes, use `inject_library_blob` on the `Device` object on the macOS side.
