### ISSUE TITLE
Can not call obj c method inside agent( error on selector)

### ISSUE THREAD

**Issue by Andre85to** [oleavr/ios-inject-custom#7]
Hi
There is a way to use objective c in the agent?
I m try to hook a function, I and wish to call some objective c method. more specifically I m try to write in a file.
On example_agent_main when I try to get the first element of an NSArray I get the error:

 NSForwarding: warning: selector (0x10d2f93c5) for message 'objectAtIndex:' does not match selector known to Objective C runtime (0x1dbd04084)-- abort
void
example_agent_main (const gchar * data, gboolean * stay_resident)
{
  GumInterceptor * interceptor;

  /* We don't want to our library to be unloaded after we return. */
  *stay_resident = TRUE;

  gum_init_embedded ();

  g_printerr ("example_agent_main()\n");

  interceptor = gum_interceptor_obtain ();
  /* Transactions are optional but improve performance with multiple hooks. */
  gum_interceptor_begin_transaction (interceptor);
  NSArray *allPaths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
  NSLog(@"allPaths = [%@] \n",allPaths);
     NSString *documentsDirectory =   NSString *documentsDirectory = [allPaths objectAtIndex:0];
   NSLog(@"documentsDirectory = [%@] \n",documentsDirectory);
   NSString *pathForLog = [documentsDirectory stringByAppendingPathComponent:@"yourFile.txt"];
     freopen([pathForLog cStringUsingEncoding:NSASCIIStringEncoding],"a+",stderr);
....

}
Can you help me to understand how to call ObjC method in C API?

**Comment by Andre85to** [comment]
for more detail, I change the makefile to compile agent.m ( I change the name from agent.c) to
$(GCC_ARM) -shared -Wl,-exported_symbol,_example_agent_main $(CFLAGS) -I$(@D)/frida-gum  agent.m -o $@ -L$(@D)/frida-core -lfrida-core -lobjc -framework Foundation $(LDFLAGS)

**Comment by Andre85to** [comment]
I got it, why and how to do. anyway thanks for the amazing job you did.

**Comment by zbw94** [comment]
> I got it, why and how to do. anyway thanks for the amazing job you did.

@Andre85to hey guy, could you tell me how to solve this problem? I have the same problem.
